// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js carga .env y .env.local automáticamente, pero el CLI de Prisma
// (migrate, db seed) no — solo lee .env por defecto. Cargamos ambos aquí a
// mano, con la misma precedencia que usa Next: .env primero, .env.local
// puede sobreescribirlo.
loadEnv();
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
